[package]
name = "catchts-service"
version = "0.1.0"
authors = ["captain-yossarian <sergiybiluk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iron = "0.4.0"